import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
	ClerkProvider,
	SignInButton,
	SignedIn,
	SignedOut,
	UserButton,
} from "@clerk/nextjs";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className={inter.className}>
					<ThemeProvider
						attribute="class"
						defaultTheme="dark"
						enableSystem
						disableTransitionOnChange
					>
						<SignedOut>
							{/* Show Sign-In Button when user is signed out */}
							<SignInButton />
						</SignedOut>
						<SignedIn>
							{/* Show User Button when user is signed in */}
							<UserButton />
						</SignedIn>
						{children}
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
